### ISSUE TITLE
Duckgo has shut down dukgo.com XMPP service.

### ISSUE THREAD

**Issue by Rendarion** [ChatSecure/chatsecure.github.io#10]
See:
https://duck.co/blog/post/4/xmpp-services-at-duckduckgo

Please remove the suggestion from the account creation function (chat service domain) drop-down menu, as it will not work.

Ty.

**Comment by chrisballinger** [comment]
It's no longer in the app, but yeah, the screenshot on the website should be updated.

**Comment by Rendarion** [comment]
I am sorry, this was supposed to be a bug-report for an Android app of the same name, which features an icon that looks identical to your logo (which is very confusing).

**Comment by chrisballinger** [comment]
Ah yeah, we broke off that partnership a while ago. Use Conversations instead.
